# Generated by Django 5.2.7 on 2025-12-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cors', '0003_account_holiday_librarybook_event_event_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
