# Generated by Django 5.2.7 on 2025-12-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cors', '0004_delete_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='semester',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
