# Generated by Django 5.2.7 on 2025-12-10 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cors', '0005_semester_created_at_semester_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='academic_system',
            field=models.CharField(choices=[('semester', 'Semester System'), ('annual', 'Annual System'), ('quarter', 'Quarter System'), ('trimester', 'Trimester System')], default='semester', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='program_level',
            field=models.CharField(choices=[('bachelor', 'Bachelor (BS/BSc)'), ('master', 'Master (MS/MSc/MPhil)'), ('phd', 'PhD/Doctorate'), ('intermediate', 'Intermediate (FSc/FA)'), ('diploma', 'Diploma/Certificate')], default='bachelor', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='total_semesters',
            field=models.IntegerField(default=8, help_text='Total semesters/parts in program'),
        ),
        migrations.AddField(
            model_name='semester',
            name='is_annual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semester',
            name='semester_type',
            field=models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer'), ('annual', 'Annual')], default='fall', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='current_semester_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_students', to='lms_cors.semester'),
        ),
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(help_text='e.g. BSCS Fall 2023', max_length=200)),
                ('session_code', models.CharField(help_text='e.g. BSCS-F23', max_length=50, unique=True)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('status', models.CharField(choices=[('admissions_open', 'Admissions Open'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='admissions_open', max_length=20)),
                ('admission_start_date', models.DateField(blank=True, null=True)),
                ('admission_end_date', models.DateField(blank=True, null=True)),
                ('class_start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_sessions', to='lms_cors.program')),
            ],
            options={
                'db_table': 'academic_sessions',
                'ordering': ['-start_year', 'program'],
                'unique_together': {('program', 'session_code')},
            },
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_session',
            field=models.ForeignKey(blank=True, help_text='The session/batch this semester belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='lms_cors.academicsession'),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='lms_cors.academicsession'),
        ),
    ]
