# Generated by Django 5.2.7 on 2025-12-10 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cors', '0006_program_academic_system_program_program_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicsession',
            options={'ordering': ['-start_year', 'program__name'], 'verbose_name': 'Academic Session', 'verbose_name_plural': 'Academic Sessions'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['academic_session', 'number'], 'verbose_name': 'Semester', 'verbose_name_plural': 'Semesters'},
        ),
        migrations.AlterUniqueTogether(
            name='academicsession',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='program',
            name='total_semesters',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_semester_obj',
        ),
        migrations.AddField(
            model_name='academicsession',
            name='current_enrollment',
            field=models.IntegerField(default=0, help_text='Current number of enrolled students'),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='expected_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='total_capacity',
            field=models.IntegerField(default=60, help_text='Maximum students in this batch'),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='total_semesters',
            field=models.IntegerField(default=8, help_text='Number of semesters/parts (auto-calculated from program type)'),
        ),
        migrations.AddField(
            model_name='program',
            name='default_semesters',
            field=models.IntegerField(blank=True, default=8, help_text='Default number of semesters/parts for this program', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='max_credit_hours',
            field=models.IntegerField(blank=True, default=140, help_text='Maximum credit hours allowed', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='min_credit_hours',
            field=models.IntegerField(blank=True, default=120, help_text='Minimum credit hours required for graduation', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='requires_internship',
            field=models.BooleanField(default=False, help_text='Does this program require an internship?'),
        ),
        migrations.AddField(
            model_name='program',
            name='requires_thesis',
            field=models.BooleanField(default=False, help_text='Does this program require a thesis?'),
        ),
        migrations.AddField(
            model_name='semester',
            name='exam_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='exam_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='result_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_semester_ref',
            field=models.ForeignKey(blank=True, help_text='Reference to current semester object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='lms_cors.semester'),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='end_year',
            field=models.IntegerField(help_text='Expected ending year'),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='program',
            field=models.ForeignKey(help_text='The program this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='lms_cors.program'),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='session_code',
            field=models.CharField(help_text='e.g., BSCS-2023 or BSCS-23', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='session_name',
            field=models.CharField(help_text='e.g., BSCS 2023-2027', max_length=200),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='start_year',
            field=models.IntegerField(help_text='Starting year'),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='academic_system',
            field=models.CharField(blank=True, choices=[('semester', 'Semester System'), ('annual', 'Annual System'), ('quarter', 'Quarter System'), ('trimester', 'Trimester System')], default='semester', help_text='Academic system (Semester, Annual, etc.)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_level',
            field=models.CharField(blank=True, choices=[('intermediate', 'Intermediate (FSC/FA)'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('diploma', 'Diploma')], default='bachelor', help_text='Level of the program (Bachelor, Master, PhD, etc.)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='academic_session',
            field=models.ForeignKey(blank=True, help_text='The academic session this semester belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='lms_cors.academicsession'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='is_annual',
            field=models.BooleanField(default=False, help_text='Is this part of an annual system?'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(help_text='e.g., Semester 1, Fall 2023', max_length=100),
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.IntegerField(help_text='Semester/Part number (1, 2, 3, etc.)'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Legacy program field (use academic_session instead)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters_legacy', to='lms_cors.program'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_type',
            field=models.CharField(blank=True, choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer'), ('annual_part1', 'Annual Part 1'), ('annual_part2', 'Annual Part 2'), ('annual_part3', 'Annual Part 3'), ('annual_part4', 'Annual Part 4'), ('quarter1', 'Quarter 1'), ('quarter2', 'Quarter 2'), ('quarter3', 'Quarter 3'), ('quarter4', 'Quarter 4')], help_text='Type of semester (Fall/Spring/Annual Part/etc.)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_session',
            field=models.ForeignKey(blank=True, help_text='The batch/session this student belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='lms_cors.academicsession'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(default=1, help_text='Current semester number (legacy)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Legacy program field (derived from academic_session)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_legacy', to='lms_cors.program'),
        ),
        migrations.AlterUniqueTogether(
            name='academicsession',
            unique_together={('program', 'start_year')},
        ),
        migrations.AlterModelTable(
            name='program',
            table='programs',
        ),
        migrations.AlterModelTable(
            name='semester',
            table='semesters',
        ),
    ]
