# Generated by Django 5.2.7 on 2025-12-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cors', '0007_alter_academicsession_options_alter_semester_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='edit_count',
            field=models.IntegerField(default=0, help_text='Number of times this session has been edited'),
        ),
    ]
