# Generated by Django 5.2.7 on 2025-12-10 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cors', '0008_academicsession_edit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubject',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this assignment is currently active'),
        ),
        migrations.AddConstraint(
            model_name='teachersubject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('subject',), name='unique_active_subject_assignment'),
        ),
    ]
