# Generated by Django 5.2.7 on 2025-12-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cors', '0009_teachersubject_assigned_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachersubject',
            unique_together=set(),
        ),
    ]
