# Generated by Django 5.2.7 on 2025-12-11 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cors', '0010_alter_teachersubject_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicsession',
            options={'ordering': ['-start_year', 'program'], 'verbose_name': 'Academic Session', 'verbose_name_plural': 'Academic Sessions'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['program', 'number']},
        ),
        migrations.RemoveConstraint(
            model_name='teachersubject',
            name='unique_active_subject_assignment',
        ),
        migrations.AlterUniqueTogether(
            name='academicsession',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='program',
            name='academic_system',
        ),
        migrations.RemoveField(
            model_name='program',
            name='default_semesters',
        ),
        migrations.RemoveField(
            model_name='program',
            name='max_credit_hours',
        ),
        migrations.RemoveField(
            model_name='program',
            name='min_credit_hours',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_level',
        ),
        migrations.RemoveField(
            model_name='program',
            name='requires_internship',
        ),
        migrations.RemoveField(
            model_name='program',
            name='requires_thesis',
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('program', 'number')},
        ),
        migrations.RemoveField(
            model_name='student',
            name='academic_session',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_semester_ref',
        ),
        migrations.AlterUniqueTogether(
            name='teachersubject',
            unique_together={('teacher', 'subject')},
        ),
        migrations.AddField(
            model_name='semester',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='lms_cors.academicsession'),
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='lms_cors.academicsession'),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='edit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='end_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='lms_cors.program'),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='session_code',
            field=models.CharField(help_text='Unique code e.g., CS-2024-F', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='session_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='start_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters_legacy', to='lms_cors.program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_legacy', to='lms_cors.program'),
        ),
        migrations.AlterModelTable(
            name='program',
            table=None,
        ),
        migrations.AlterModelTable(
            name='semester',
            table=None,
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='admission_end_date',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='admission_start_date',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='class_start_date',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='current_enrollment',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='expected_end_date',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='total_capacity',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='total_semesters',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='academic_session',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='exam_end_date',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='exam_start_date',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='is_annual',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='result_date',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='semester_type',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='assigned_date',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='is_active',
        ),
    ]
