# Generated by Django 5.2.7 on 2025-12-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cors', '0011_alter_academicsession_options_alter_semester_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AddField(
            model_name='program',
            name='academic_system',
            field=models.CharField(choices=[('semester', 'Semester System'), ('annual', 'Annual System')], default='semester', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='default_semesters',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='program',
            name='max_credit_hours',
            field=models.IntegerField(default=140),
        ),
        migrations.AddField(
            model_name='program',
            name='min_credit_hours',
            field=models.IntegerField(default=130),
        ),
        migrations.AddField(
            model_name='program',
            name='program_level',
            field=models.CharField(choices=[('bachelor', 'Bachelor (BS)'), ('master', 'Master (MS/MPhil)'), ('phd', 'Doctorate (PhD)'), ('intermediate', 'Intermediate (FSc/FA)'), ('diploma', 'Diploma/Certificate')], default='bachelor', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='requires_internship',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program',
            name='requires_thesis',
            field=models.BooleanField(default=False),
        ),
    ]
