# Generated by Django 5.2.7 on 2025-12-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cors', '0012_alter_program_options_program_academic_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='total_capacity',
            field=models.IntegerField(default=60, help_text='Maximum students allowed in this session'),
        ),
    ]
