# Generated by Django 5.2.7 on 2025-12-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cors', '0013_add_total_capacity_to_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
