# Generated by Django 5.2.7 on 2025-12-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cors', '0014_program_created_at_program_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubject',
            name='assigned_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this assignment currently active?'),
        ),
    ]
